workflows:
    issue_flow:
        transition_definitions:
            start_progress_definition: ~
            stop_progress_definition: ~
            resolved_definition: ~
            closed_definition: ~
            reopen_definition:
                post_actions:
                    - '@assign_value':
                        - [$issue_resolution, ~]
