workflows:
    issue_flow:
        transitions:
            start_progress:
                step_to: in_progress
                frontend_options:
                    icon: 'icon-play'
                    class: 'btn-primary'
                transition_definition: start_progress_definition
            stop_progress:
                step_to: open
                frontend_options:
                    icon: 'icon-stop'
                    class: 'btn-primary'
                transition_definition: stop_progress_definition
            resolve:
                step_to: resolved
                frontend_options:
                    icon: 'icon-star'
                transition_definition: resolved_definition
                form_options:
                    attribute_fields:
                        issue_resolution:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
            close:
                step_to: closed
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
                form_options:
                    attribute_fields:
                        issue_resolution:
                            options:
                                required: true
                                constraints:
                                    - NotBlank: ~
            reopen:
                step_to: open
                frontend_options:
                    icon: 'icon-refresh'
                transition_definition: reopen_definition
