workflows:
    issue_flow:
        steps:
            open:
                order: 10
                allowed_transitions:
                    - start_progress
                    - resolve
                    - close
            in_progress:
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
                    - close
            resolved:
                order: 30
                allowed_transitions:
                    - close
                    - reopen
            closed:
                order: 40
                allowed_transitions:
                    - reopen
