parameters:
    oro_bug_tracking_system.condition.is_instance_of.class: Oro\Bundle\BugTrackingSystemBundle\Model\Condition\IsInstanceOf

services:
    oro_bug_tracking_system.condition.is_instance_of:
        class: '%oro_bug_tracking_system.condition.is_instance_of.class%'
        tags:
            - { name: oro_workflow.condition, alias: is_instance_of }
