datagrid:
    issues_grid:
        extended_entity_name: %oro_bug_tracking_system.issue.entity.class%
        source:
            type: orm
#            acl_resource: orocrm_task_view
            query:
                select:
                    - issue.id
                    - issue.summary
                    - issue.description
                    - issueType.label as typeLabel
                    - issuePriority.label as priorityLabel
                    - issueResolution.label as resolutionLabel
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - reporter.id as reporterId
                    - CONCAT(assignee.firstName, CONCAT(' ', assignee.lastName)) as assigneeName
                    - assignee.id as assigneeId
                    - issue.createdAt
                    - issue.updatedAt
#                    - workflowStep.label as workflowStepLabel
                from:
                    - { table: %oro_bug_tracking_system.issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.issueType, alias: issueType }
                        - { join: issue.issuePriority, alias: issuePriority }
                        - { join: issue.issueResolution, alias: issueResolution }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.assignee, alias: assignee }
#                        - { join: task.workflowStep, alias: workflowStep }
        columns:
            summary:
                label:         oro.bugtrackingsystem.issue.summary.label
#            workflowStepLabel:
#                label:         orocrm.task.workflow_step.label
            typeLabel:
                label:         oro.bugtrackingsystem.issue.issue_type.label
            priorityLabel:
                label:         oro.bugtrackingsystem.issue.issue_priority.label
            resolutionLabel:
                label:         oro.bugtrackingsystem.issue.issue_resolution.label
            reporterName:
                type:          twig
                label:         oro.bugtrackingsystem.issue.reporter.label
                frontend_type: html
                template:      OroBugTrackingSystemBundle:Issue:Datagrid/Property/reporter.html.twig
            assigneeName:
                type:          twig
                label:         oro.bugtrackingsystem.issue.assignee.label
                frontend_type: html
                template:      OroBugTrackingSystemBundle:Issue:Datagrid/Property/assignee.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                summary:
                    data_name: issue.summary
#                workflowStepLabel:
#                    data_name: workflowStep.stepOrder
                typeLabel:
                    data_name: issueType.order
                priorityLabel:
                    data_name: issuePriority.order
                resolutionLabel:
                    data_name: issueResolution.order
                reporterName:
                    data_name: reporterName
                assigneeName:
                    data_name: assigneeName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                dueDate: ASC
        filters:
            columns:
                summary:
                    type:      string
                    data_name: issue.summary
#                workflowStepLabel:
#                    type:      entity
#                    data_name: task.workflowStep
#                    options:
#                        field_type: oro_workflow_step_select
#                        field_options:
#                            workflow_entity_class: %orocrm_task.entity.class%
                typeLabel:
                    type:      string
                    data_name: typeLabel
                priorityLabel:
                    type:      string
                    data_name: priorityLabel
                resolutionLabel:
                    type:      string
                    data_name: resolutionLabel
                reporterName:
                    type:      string
                    data_name: reporterName
                assigneeName:
                    type:      string
                    data_name: assigneeName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
#        properties:
#            id: ~
#            view_link:
#                type:       url
#                route:      orocrm_task_view
#                params:     [ id ]
#            update_link:
#                type:       url
#                route:      orocrm_task_update
#                params:     [ id ]
#            delete_link:
#                type:       url
#                route:      orocrm_api_delete_task
#                params:     [ id ]
#        actions:
#            view:
#                type:          navigate
#                acl_resource:  orocrm_task_view
#                label:         oro.grid.action.view
#                icon:          eye-open
#                link:          view_link
#                rowAction:     true
#            update:
#                type:          navigate
#                acl_resource:  orocrm_task_update
#                label:         oro.grid.action.update
#                icon:          edit
#                link:          update_link
#            delete:
#                type:          delete
#                acl_resource:  orocrm_task_delete
#                label:         oro.grid.action.delete
#                icon:          trash
#                link:          delete_link
        options:
            entity_pagination: true

#    widget-base-tasks-grid:
#        source:
#            type: orm
#            acl_resource: orocrm_task_view
#            query:
#                select:
#                    - task.id
#                    - task.subject
#                    - task.dueDate
#                    - taskPriority.label as priorityLabel
#                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
#                    - owner.id as ownerId
#                    - workflowStep.label as workflowStepLabel
#                from:
#                    - { table: %orocrm_task.entity.class%, alias: task }
#                join:
#                    left:
#                        - { join: task.taskPriority, alias: taskPriority }
#                        - { join: task.owner, alias: owner }
#                        - { join: task.workflowStep, alias: workflowStep }
#        columns:
#            subject:
#                label:         orocrm.task.subject.label
#                type:          twig
#                template:      OroCRMTaskBundle:Task:Datagrid/Property/subject.html.twig
#                frontend_type: html
#            dueDate:
#                label:         orocrm.task.due_date.label
#                frontend_type: datetime
#            workflowStepLabel:
#                label:         orocrm.task.workflow_step.label
#            priorityLabel:
#                label:         orocrm.task.task_priority.label
#            ownerName:
#                type:          twig
#                label:         orocrm.task.owner.label
#                frontend_type: html
#                template:      OroCRMTaskBundle:Task:Datagrid/Property/owner.html.twig
#        sorters:
#            columns:
#                subject:
#                    data_name: task.subject
#                dueDate:
#                    data_name: task.dueDate
#                workflowStepLabel:
#                    data_name: workflowStep.stepOrder
#                priorityLabel:
#                    data_name: taskPriority.order
#                ownerName:
#                    data_name: ownerName
#            default:
#                dueDate: ASC
#        filters:
#            columns:
#                subject:
#                    type:      string
#                    data_name: task.subject
#                dueDate:
#                    type:      datetime
#                    data_name: task.dueDate
#                workflowStepLabel:
#                    type:      entity
#                    data_name: task.workflowStep
#                    options:
#                        field_type: oro_workflow_step_select
#                        field_options:
#                            workflow_entity_class: %orocrm_task.entity.class%
#                priorityLabel:
#                    type:      string
#                    data_name: priorityLabel
#                ownerName:
#                    type:      string
#                    data_name: ownerName
#        properties:
#            id: ~

#    activity-tasks-grid:
#        extends: widget-base-tasks-grid
#
#    user-tasks-grid:
#        extends: tasks-grid
#        options:
#            entity_pagination: false
