datagrid:
    issues_grid:
        extended_entity_name: %oro_bug_tracking_system.issue.entity.class%
        source:
            type: orm
            acl_resource: oro_bug_tracking_system_issue_view
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - issue.description
                    - issueType.label as typeLabel
                    - issuePriority.label as priorityLabel
                    - workflowStep.label as workflowStepLabel
                    - issueResolution.label as resolutionLabel
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - reporter.id as reporterId
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - owner.id as ownerId
                    - issue.createdAt
                    - issue.updatedAt
                from:
                    - { table: %oro_bug_tracking_system.issue.entity.class%, alias: issue }
                join:
                    left:
                        - { join: issue.issueType, alias: issueType }
                        - { join: issue.issuePriority, alias: issuePriority }
                        - { join: issue.issueResolution, alias: issueResolution }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.owner, alias: owner }
                        - { join: issue.workflowStep, alias: workflowStep }
        columns:
            code:
                label:         oro.bugtrackingsystem.issue.code.label
            summary:
                label:         oro.bugtrackingsystem.issue.summary.label
            typeLabel:
                label:         oro.bugtrackingsystem.issue.issue_type.label
            priorityLabel:
                label:         oro.bugtrackingsystem.issue.issue_priority.label
            workflowStepLabel:
                label:         oro.bugtrackingsystem.issue.workflow_step.label
            resolutionLabel:
                label:         oro.bugtrackingsystem.issue.issue_resolution.label
            reporterName:
                type:          twig
                label:         oro.bugtrackingsystem.issue.reporter.label
                frontend_type: html
                template:      OroBugTrackingSystemBundle:Issue:Datagrid/Property/reporter.html.twig
            ownerName:
                type:          twig
                label:         oro.bugtrackingsystem.issue.owner.label
                frontend_type: html
                template:      OroBugTrackingSystemBundle:Issue:Datagrid/Property/owner.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                typeLabel:
                    data_name: issueType.order
                priorityLabel:
                    data_name: issuePriority.order
                workflowStepLabel:
                    data_name: workflowStep.stepOrder
                resolutionLabel:
                    data_name: issueResolution.order
                reporterName:
                    data_name: reporterName
                ownerName:
                    data_name: ownerName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type:      string
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                typeLabel:
                    type:      entity
                    data_name: issueType.id
                    options:
                        field_options:
                            class: %oro_bug_tracking_system.issue_type.entity.class%
                            property: label
                priorityLabel:
                    type:      entity
                    data_name: issuePriority.id
                    options:
                        field_options:
                            class: %oro_bug_tracking_system.issue_priority.entity.class%
                            property: label
                workflowStepLabel:
                    type:      entity
                    data_name: issue.workflowStep
                    options:
                        field_type: oro_workflow_step_select
                        field_options:
                            workflow_entity_class: %oro_bug_tracking_system.issue.entity.class%
                resolutionLabel:
                    type:      entity
                    data_name: issueResolution.id
                    options:
                        field_options:
                            class: %oro_bug_tracking_system.issue_resolution.entity.class%
                            property: label
                reporterName:
                    type:      string
                    data_name: reporterName
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_bug_tracking_system_issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_bug_tracking_system_issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_bug_tracking_system_api_delete_issue
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_bug_tracking_system_issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_bug_tracking_system_issue_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
#            delete:
#                type:          delete
#                acl_resource:  oro_bug_tracking_system_issue_delete
#                label:         oro.grid.action.delete
#                icon:          trash
#                link:          delete_link
            delete:
                type:          story-delete
                acl_resource:  oro_bug_tracking_system_issue_delete
                label:         oro.grid.action.delete
                icon:          ok
                link:          delete_link
        options:
            entity_pagination: true

    subtask_grid:
        extends: issues_grid
        source:
            query:
                where:
                    and:
                        - issue.parent = :issue_id
            bind_parameters:
                - issue_id
        columns:
            typeLabel:
                renderable: false
        filters:
            columns:
                typeLabel:
                    enabled: false

    user_issues_grid:
        extends: issues_grid
        options:
            entity_pagination: false

    collaborators_grid:
        source:
            type: orm
            acl_resource: oro_bug_tracking_system_issue_view
            query:
                select:
                    - collaborator.id
                    - CONCAT(collaborator.firstName, CONCAT(' ', collaborator.lastName)) as collaboratorName
                from:
                    - { table: %oro_bug_tracking_system.issue.entity.class%, alias: issue }
                join:
                    inner:
                        - { join: issue.collaborators , alias: collaborator }
                where:
                    and:
                        - issue.id = :issue_id
            bind_parameters:
                - issue_id
        columns:
            collaboratorName:
                label:         oro.bugtrackingsystem.collaborator.entity_label
        sorters:
            columns:
                collaboratorName:
                    data_name: collaboratorName
            default:
                collaboratorName: ASC
        filters:
            columns:
                collaboratorName:
                    type:      string
                    data_name: collaboratorName
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_user_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_user_user_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true