parameters:
    oro_bug_tracking_system.form.type.issue.class:     Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueType
    oro_bug_tracking_system.form.type.issue_api.class: Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueApiType
    oro_bug_tracking_system.form.handler.issue.class:  Oro\Bundle\BugTrackingSystemBundle\Form\Handler\IssueHandler
    oro_bug_tracking_system.manager.api.class:         Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    oro_bug_tracking_system.form.type.issue:
        class: %oro_bug_tracking_system.form.type.issue.class%
        tags:
            - { name: form.type, alias: oro_bug_tracking_system_issue }
            
    oro_bug_tracking_system.form.type.issue_api:
        class: %oro_bug_tracking_system.form.type.issue_api.class%
        tags:
            - { name: form.type, alias: oro_bug_tracking_system_issue_api }

    oro_bug_tracking_system.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'oro_bug_tracking_system_issue_form'
            - 'oro_bug_tracking_system_issue'

    oro_bug_tracking_system.form.handler.issue:
        class: %oro_bug_tracking_system.form.handler.issue.class%
        scope: request
        arguments:
            - @oro_bug_tracking_system.form
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    oro_bug_tracking_system.form.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - 'oro_bug_tracking_system_issue_api'

    oro_bug_tracking_system.form.handler.issue_api:
        class: %oro_bug_tracking_system.form.handler.issue.class%
        scope: request
        arguments:
            - @oro_bug_tracking_system.form.api
            - @request
            - @doctrine.orm.entity_manager
        tags:
            - { name: oro_tag.tag_manager }

    oro_bug_tracking_system.manager.api:
        class: %oro_bug_tracking_system.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_bug_tracking_system.issue.entity.class%
            - @doctrine.orm.entity_manager