parameters:
    oro_bug_tracking_system.form.type.issue.class:    Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueType
    oro_bug_tracking_system.form.handler.issue.class: Oro\Bundle\BugTrackingSystemBundle\Form\Handler\IssueHandler

services:
    oro_bug_tracking_system.form.type.issue:
        class: %oro_bug_tracking_system.form.type.issue.class%
        tags:
            - { name: form.type, alias: oro_bug_tracking_system_issue }

    oro_bug_tracking_system.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'oro_bug_tracking_system_issue'
            - 'oro_bug_tracking_system_issue'

    oro_bug_tracking_system.form.handler.issue:
        class: %oro_bug_tracking_system.form.handler.issue.class%
        scope: request
        arguments:
            - @oro_bug_tracking_system.form
            - @request
            - @doctrine.orm.entity_manager
            - @oro_activity.manager
            - @oro_entity.routing_helper
