parameters:
    oro_bug_tracking_system.form.type.issue.class:         Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueType
    oro_bug_tracking_system.form.type.issue_api.class:     Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueApiType
    oro_bug_tracking_system.form.type.issue_select.class:  Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueSelectType
    oro_bug_tracking_system.form.type.link_issue.class:    Oro\Bundle\BugTrackingSystemBundle\Form\Type\LinkIssueType
    oro_bug_tracking_system.form.handler.issue.class:      Oro\Bundle\BugTrackingSystemBundle\Form\Handler\IssueHandler
    oro_bug_tracking_system.form.handler.link_issue.class: Oro\Bundle\BugTrackingSystemBundle\Form\Handler\LinkIssueHandler
    oro_bug_tracking_system.manager.api.class:             Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    oro_bug_tracking_system.form.type.issue:
        class: '%oro_bug_tracking_system.form.type.issue.class%'
        tags:
            - { name: form.type }
            
    oro_bug_tracking_system.form.type.issue_api:
        class: '%oro_bug_tracking_system.form.type.issue_api.class%'
        tags:
            - { name: form.type }

    oro_bug_tracking_system.form:
        class: Symfony\Component\Form\Form
        factory: [ '@form.factory', createNamed ]
        arguments:
            - 'oro_bug_tracking_system_issue_form'
            - 'Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueType'

    oro_bug_tracking_system.form.handler.issue:
        class: '%oro_bug_tracking_system.form.handler.issue.class%'
        scope: request
        shared: false
        arguments:
            - '@oro_bug_tracking_system.form'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
            - '@oro_activity.manager'
            - '@oro_entity.routing_helper'
        tags:
            - { name: oro_tag.tag_manager }

    oro_bug_tracking_system.form.api:
        class: Symfony\Component\Form\Form
        factory: [ '@form.factory', createNamed ]
        arguments:
            - ~
            - 'Oro\Bundle\BugTrackingSystemBundle\Form\Type\IssueApiType'

    oro_bug_tracking_system.form.handler.issue_api:
        class: '%oro_bug_tracking_system.form.handler.issue.class%'
        scope: request
        shared: false
        arguments:
            - '@oro_bug_tracking_system.form.api'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
            - '@oro_activity.manager'
            - '@oro_entity.routing_helper'
        tags:
            - { name: oro_tag.tag_manager }

    oro_bug_tracking_system.manager.api:
        class: '%oro_bug_tracking_system.manager.api.class%'
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - '%oro_bug_tracking_system.issue.entity.class%'
            - '@doctrine.orm.entity_manager'

    oro_bug_tracking_system.form.type.issue_select:
        class: '%oro_bug_tracking_system.form.type.issue_select.class%'
        tags:
            - { name: form.type }

    oro_bug_tracking_system.form.autocomplete.issue.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%oro_bug_tracking_system.issue.entity.class%'
            - ["code", "summary"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: issues, acl_resource: oro_bug_tracking_system_issue_view }

    oro_bug_tracking_system.form.type.link_issue:
        class: '%oro_bug_tracking_system.form.type.link_issue.class%'
        tags:
            - { name: form.type, alias: oro_bug_tracking_system_link_issue }

    oro_bug_tracking_system.form.link_issue:
        class: Symfony\Component\Form\Form
        factory: [ '@form.factory', createNamed ]
        arguments:
            - 'oro_bug_tracking_system_link_issue_form'
            - 'oro_bug_tracking_system_link_issue'

    oro_bug_tracking_system.form.handler.link_issue:
        class: '%oro_bug_tracking_system.form.handler.link_issue.class%'
        scope: request
        shared: false
        arguments:
            - '@oro_bug_tracking_system.form.link_issue'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
