oro_menu_config:
    items:
        issue_list:
            label: 'oro.bugtrackingsystem.issue.entity_plural_label'
            route: 'oro_bug_tracking_system_issue_index'
            extras:
                position: 10
                routes:
                    - 'oro_bug_tracking_system_issue_update'
                    - 'oro_bug_tracking_system_issue_create'
                    - 'oro_bug_tracking_system_issue_view'
                description: 'oro.bugtrackingsystem.issue.menu.issue_list.description'

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        issue_list: ~

oro_titles:
    oro_bug_tracking_system_issue_index: ~
    oro_bug_tracking_system_issue_view: '%%entityCode%%'
    oro_bug_tracking_system_issue_create: oro.ui.create_entity
    oro_bug_tracking_system_issue_update: '%%entityCode%% - Edit'