placeholders:
    view_content_data_additional_information:
        items:
            oro_bug_tracking_system_user_issues: ~
    view_navButtons_after:
        items:
            oro_bug_tracking_system_user_create_issue_button:
                order: 500

items:
    oro_bug_tracking_system_user_issues:
        template: OroBugTrackingSystemBundle:Issue:userIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: oro_bug_tracking_system_issue_view

    oro_bug_tracking_system_user_create_issue_button:
        template: OroBugTrackingSystemBundle:Issue:createIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: oro_bug_tracking_system_issue_create