config:
    paths:
        'orobugtrackingsystem/js/issue-deletion-handler': 'bundles/orobugtrackingsystem/js/issue-deletion-handler.js'
        'oro/datagrid/action/issue-delete-action':        'bundles/orobugtrackingsystem/js/datagrid/action/issue-delete-action.js'
