parameters:
    oro_bug_tracking_system.issue.entity.class:   Oro\Bundle\BugTrackingSystemBundle\Entity\Issue
    oro_bug_tracking_system.issue.listener.class: Oro\Bundle\BugTrackingSystemBundle\EventListener\IssueListener

services:
    oro_bug_tracking_system.issue.listener:
        class: %oro_bug_tracking_system.issue.listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }