parameters:
    oro_bug_tracking_system.issue.entity.class:   Oro\Bundle\BugTrackingSystemBundle\Entity\Issue
    oro_bug_tracking_system.issue.listener.class: Oro\Bundle\BugTrackingSystemBundle\EventListener\IssueListener

services:
    oro_bts_issue.listener:
        class: %oro_bug_tracking_system.issue.listener.class%
        tags:
            - { name: doctrine.event_listener, event: postFlush }
