parameters:
    oro_bug_tracking_system.issue.entity.class: Oro\Bundle\BugTrackingSystemBundle\Entity\Issue

services:
#    oro_bug_tracking_system.example:
#        class: %oro_bug_tracking_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
