parameters:
    oro_bug_tracking_system.issue.entity.class:   Oro\Bundle\BugTrackingSystemBundle\Entity\Issue
    oro_bug_tracking_system.issue.listener.class: Oro\Bundle\BugTrackingSystemBundle\EventListener\IssueListener

    oro_bug_tracking_system.manager.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    oro_bug_tracking_system.issue.listener:
        class: %oro_bug_tracking_system.issue.listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }

    oro_bug_tracking_system.issue.manager.api:
        class: %oro_bug_tracking_system.manager.api.class%
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
            - %oro_bug_tracking_system.issue.entity.class%
            - @doctrine.orm.entity_manager