parameters:
    oro_bug_tracking_system.issue.entity.class:            Oro\Bundle\BugTrackingSystemBundle\Entity\Issue
    oro_bug_tracking_system.issue_priority.entity.class:   Oro\Bundle\BugTrackingSystemBundle\Entity\IssuePriority
    oro_bug_tracking_system.issue_resolution.entity.class: Oro\Bundle\BugTrackingSystemBundle\Entity\IssueResolution
    oro_bug_tracking_system.issue_type.entity.class:       Oro\Bundle\BugTrackingSystemBundle\Entity\IssueType

    oro_bug_tracking_system.issue.listener.class:          Oro\Bundle\BugTrackingSystemBundle\EventListener\IssueListener

    oro_bug_tracking_system.datagrid.action.issue_delete.class: Oro\Bundle\BugTrackingSystemBundle\Datagrid\Action\IssueDeleteAction

services:
    oro_bug_tracking_system.issue.listener:
        class: %oro_bug_tracking_system.issue.listener.class%
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }

    oro_bug_tracking_system.datagrid.action.issue_delete:
        class: %oro_bug_tracking_system.datagrid.action.issue_delete.class%
        scope: prototype
        tags:
            - { name: oro_datagrid.extension.action.type, type: issue-delete }