parameters:
#    oro_bug_tracking_system.example.class: Oro\Bundle\BugTrackingSystemBundle\Example

services:
#    oro_bug_tracking_system.example:
#        class: %oro_bug_tracking_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
