Oro\Bundle\BugTrackingSystemBundle\Entity\Issue:
    properties:
        summary:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        description:
            - Length:
                max: 255
        issuePriority:
            - NotBlank: ~
        issueType:
            - NotBlank: ~
        owner:
            - NotBlank: ~
        children: ~