datagrids:
    issues-grid:
        extended_entity_name: '%oro_bug_tracking_system.issue.entity.class%'
        source:
            type: orm
            acl_resource: oro_bug_tracking_system_issue_view
            query:
                select:
                    - issue.id
                    - issue.code
                    - issue.summary
                    - issue.description
                    - issueType.label as typeLabel
                    - issuePriority.label as priorityLabel
                    - issueResolution.label as resolutionLabel
                    - CONCAT(reporter.firstName, CONCAT(' ', reporter.lastName)) as reporterName
                    - reporter.id as reporterId
                    - CONCAT(owner.firstName, CONCAT(' ', owner.lastName)) as ownerName
                    - owner.id as ownerId
                    - issue.createdAt
                    - issue.updatedAt
                    - COUNT(DISTINCT subtask.id) as subtasksCount
                from:
                    - { table: '%oro_bug_tracking_system.issue.entity.class%', alias: issue }
                join:
                    left:
                        - { join: issue.issueType, alias: issueType }
                        - { join: issue.issuePriority, alias: issuePriority }
                        - { join: issue.issueResolution, alias: issueResolution }
                        - { join: issue.reporter, alias: reporter }
                        - { join: issue.owner, alias: owner }
                        - { join: issue.children, alias: subtask }
                groupBy: issue.id
        columns:
            code:
                label:         oro.bugtrackingsystem.issue.code.label
            summary:
                label:         oro.bugtrackingsystem.issue.summary.label
            typeLabel:
                label:         oro.bugtrackingsystem.issue.issue_type.label
            priorityLabel:
                label:         oro.bugtrackingsystem.issue.issue_priority.label
            resolutionLabel:
                label:         oro.bugtrackingsystem.issue.issue_resolution.label
            reporterName:
                type:          twig
                label:         oro.bugtrackingsystem.issue.reporter.label
                frontend_type: html
                template:      OroBugTrackingSystemBundle:Issue:Datagrid/Property/reporter.html.twig
            ownerName:
                type:          twig
                label:         oro.bugtrackingsystem.issue.owner.label
                frontend_type: html
                template:      OroBugTrackingSystemBundle:Issue:Datagrid/Property/owner.html.twig
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
            subtasksCount:
                renderable:    false
        sorters:
            columns:
                code:
                    data_name: issue.code
                summary:
                    data_name: issue.summary
                typeLabel:
                    data_name: issueType.entityOrder
                priorityLabel:
                    data_name: issuePriority.entityOrder
                resolutionLabel:
                    data_name: issueResolution.entityOrder
                reporterName:
                    data_name: reporterName
                ownerName:
                    data_name: ownerName
                createdAt:
                    data_name: issue.createdAt
                updatedAt:
                    data_name: issue.updatedAt
            default:
                updatedAt: DESC
        filters:
            columns:
                code:
                    type:      string
                    data_name: issue.code
                summary:
                    type:      string
                    data_name: issue.summary
                typeLabel:
                    type:      entity
                    data_name: issueType.id
                    options:
                        field_options:
                            class: '%oro_bug_tracking_system.issue_type.entity.class%'
                            property_path: label
                priorityLabel:
                    type:      entity
                    data_name: issuePriority.id
                    options:
                        field_options:
                            class: '%oro_bug_tracking_system.issue_priority.entity.class%'
                            property_path: label
                resolutionLabel:
                    type:      entity
                    data_name: issueResolution.id
                    options:
                        field_options:
                            class: '%oro_bug_tracking_system.issue_resolution.entity.class%'
                            property_path: label
                reporterName:
                    type:      string
                    data_name: reporterName
                ownerName:
                    type:      string
                    data_name: ownerName
                createdAt:
                    type:      datetime
                    data_name: issue.createdAt
                updatedAt:
                    type:      datetime
                    data_name: issue.updatedAt
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_bug_tracking_system_issue_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_bug_tracking_system_issue_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_bug_tracking_system_api_delete_issue
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_bug_tracking_system_issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_bug_tracking_system_issue_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          issue-delete
                acl_resource:  oro_bug_tracking_system_issue_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
        options:
            entity_pagination: true

    subtask_grid:
        extends: issues-grid
        source:
            query:
                where:
                    and:
                        - issue.parent = :issue_id
            bind_parameters:
                - issue_id
        columns:
            typeLabel:
                renderable: false
        filters:
            columns:
                typeLabel:
                    enabled: false

    dashboard-user-issues-grid:
        extends: issues-grid
        source:
            query:
                join:
                    left:
                        - { join: issue.collaborators, alias: collaborator }
                where:
                    and:
                        - 'collaborator.id = @oro_security.security_facade->getLoggedUserId'
        columns:
            typeLabel:
                renderable:    false
            resolutionLabel:
                renderable:    false
            reporterName:
                renderable:    false
            createdAt:
                renderable:    false
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    user-issues-grid:
        extends: issues-grid
        source:
            query:
                where:
                    or:
                        - issue.owner = :userId
                        - issue.reporter = :userId
            bind_parameters:
                - userId
        filters: ~
        options:
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    collaborators_grid:
        source:
            type: orm
            acl_resource: oro_bug_tracking_system_issue_view
            query:
                select:
                    - collaborator.id
                    - CONCAT(collaborator.firstName, CONCAT(' ', collaborator.lastName)) as collaboratorName
                from:
                    - { table: '%oro_bug_tracking_system.issue.entity.class%', alias: issue }
                join:
                    inner:
                        - { join: issue.collaborators , alias: collaborator }
                where:
                    and:
                        - issue.id = :issue_id
            bind_parameters:
                - issue_id
        columns:
            collaboratorName:
                label:         oro.bugtrackingsystem.collaborator.entity_label
        sorters:
            columns:
                collaboratorName:
                    data_name: collaboratorName
            default:
                collaboratorName: ASC
        filters: ~
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_user_view
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_user_user_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true

    related-issues-grid:
        source:
            type: orm
            acl_resource: oro_bug_tracking_system_issue_view
            query:
                select:
                    - relatedIssue.id
                    - relatedIssue.code
                    - relatedIssue.summary
                    - relatedIssueType.label as typeLabel
                    - relatedIssuePriority.label as priorityLabel
                    - issue.id AS mainId
                from:
                    - { table: '%oro_bug_tracking_system.issue.entity.class%', alias: issue }
                join:
                    inner:
                        - { join: issue.relatedIssues, alias: relatedIssue }
                    left:
                        - { join: relatedIssue.issueType, alias: relatedIssueType }
                        - { join: relatedIssue.issuePriority, alias: relatedIssuePriority }
                where:
                    and:
                        - issue.id = :issue_id
                orderBy:
                    - column: relatedIssue.id
                      dir: asc
            bind_parameters:
                - issue_id
        columns:
            code:
                label:         oro.bugtrackingsystem.issue.code.label
            summary:
                label:         oro.bugtrackingsystem.issue.summary.label
            typeLabel:
                label:         oro.bugtrackingsystem.issue.issue_type.label
            priorityLabel:
                label:         oro.bugtrackingsystem.issue.issue_priority.label
        properties:
            id: ~
            mainId: ~
            view_link:
                type:       url
                route:      oro_bug_tracking_system_issue_view
                params:     [ id ]
            unlink_link:
                type:       url
                route:      oro_bug_tracking_system_issue_unlink
                params:
                     - mainId
                     - id
        actions:
            view:
                type:          navigate
                acl_resource:  oro_bug_tracking_system_issue_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            unlink:
                type:          issue-unlink
                acl_resource:  oro_bug_tracking_system_issue_update
                label:         oro.bugtrackingsystem.issue.button.unlink
                icon:          eraser
                link:          unlink_link
