Oro\Bundle\BugTrackingSystemBundle\Entity\Issue:
    properties:
        summary:
            - NotBlank: ~
            - Length:
                min: 3
                max: 255
        issuePriority:
            - NotBlank: ~
        issueType:
            - NotBlank: ~
        owner:
            - NotBlank: ~

Oro\Bundle\BugTrackingSystemBundle\Entity\IssuePriority:
    properties:
        name:
            - NotBlank: ~
        label:
            - NotBlank: ~

Oro\Bundle\BugTrackingSystemBundle\Entity\IssueResolution:
    properties:
        name:
            - NotBlank: ~
        label:
            - NotBlank: ~

Oro\Bundle\BugTrackingSystemBundle\Entity\IssueType:
    properties:
        name:
            - NotBlank: ~
        label:
            - NotBlank: ~