workflows:
    issue_flow:
        transitions:
            start_progress:
                label: 'Start progress'
                step_to: in_progress
                frontend_options:
                    icon: 'icon-play'
                    class: 'btn-primary'
                transition_definition: start_progress_definition
            stop_progress:
                label: 'Stop progress'
                step_to: open
                frontend_options:
                    icon: 'icon-stop'
                    class: 'btn-primary'
                transition_definition: stop_progress_definition
            resolve:
                label: 'Resolve'
                step_to: resolved
                frontend_options:
                    icon: 'icon-star'
                transition_definition: resolved_definition
                form_options:
                    attribute_fields:
                        issue_resolution:
                            form_type: entity
                            options:
                                class: Oro\Bundle\BugTrackingSystemBundle\Entity\IssueResolution
                                property: label
                                required: true
            close:
                label: 'Close'
                step_to: closed
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
                form_options:
                    attribute_fields:
                        issue_resolution:
                            form_type: entity
                            options:
                                class: Oro\Bundle\BugTrackingSystemBundle\Entity\IssueResolution
                                property: label
                                required: true
            reopen:
                label: 'Reopen'
                step_to: open
                frontend_options:
                    icon: 'icon-refresh'
                transition_definition: reopen_definition